# mariadb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  MARIADB_ROOT_PASSWORD: "rootpassword"
  MARIADB_DATABASE: "wordpress"
  MARIADB_USER: "wpuser"
  MARIADB_PASSWORD: "wppassword"
---
# mariadb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None  # Headless Service, 用于 StatefulSet 和特定情况
---
# mariadb-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/bitnami/mariadb:10.4
      envFrom:
        - configMapRef:
            name: mariadb-config
      ports:
        - containerPort: 3306
