apiVersion: v1
kind: Pod
metadata:
  name: maria-pod
  labels:
    app: wordpress
    role: database

spec:
  containers:
    - image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/bitnami/mariadb:10.4
      name: maria
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306

      envFrom:
        - prefix: 'MARIADB_'
          configMapRef:
            name: maria-cm