apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WORDPRESS_DB_HOST: "mariadb:3306"
  WORDPRESS_DB_USER: "wpuser"
  WORDPRESS_DB_PASSWORD: "wppassword"
  WORDPRESS_DB_NAME: "wordpress"
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
    - image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/wordpress:6.2.2
      name: wordpress
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: wordpress-config
