apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wordpress
    role: website

spec:
  containers:
    - image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/wordpress:6.2.2
      name: wp-pod
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80

      envFrom:
        - prefix: 'WORDPRESS_DB_'
          configMapRef:
            name: wp-cm
