version: '3.8'
services:
  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: rouyi-vue-pro
    volumes:
      - ../sql/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"